spring:
 application:
  name: OnlineShoppingApplication
 datasource:
  url: jdbc:mysql://localhost:3306/Online_Shopping_Application?createDatabaseIfNotExist=true
  username: ${datasource.username}
  password: ${datasource.password}
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa: 
  show-sql: true
  hibernate:
   ddl-auto: update
#SMTP Configuration

 mail:
  host: smtp.gmail.com
  port: 587
  username: ${mail.username}
  password: ${mail.password}
  properties: 
   mail:
    smtp:
     starttls:
      enable: true
      required: true
  
  
 